services:
  - type: web
    name: flask-server
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r ai_model/requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: CFLAGS
        value: "-O3"
