import React, { useState } from "react";

import axios from "axios";
const cities = {
  Delhi: [
    "Vasant Vihar",
    "Rohini Sector 24",
    "Rohini Sector 8",
    "Defence Colony",
    "Hauz Khas",
    "Kishangarh",
    "Kesarwani Apartment",
    "Guru Apartment",
    "Uttam Nagar",
    "DLF Capital Greens 1 and 2",
    "Prestige Apartments",
    "Himachal Dauladhar",
    "Executive Floor",
    "IES Officers Apartment",
    "Hind Apartment",
    "The Vimal Apartment",
    "Dwarka Mor",
    "New Friends Colony New Delhi",
    "DDA Metro View Apartments",
    "Govindpuri Main",
    "Dwarka Mor",
    "DDA Metro View Apartments",
    "Anusandhan Apartment",
    "Apna Villa Apartment",
    "Fakhrudd Apartments",
    "DDA Platinum Heights",
    "Kanak Durga Apartment",
    "DDA Flats Sarita Vihar",
    "Prem Milan Apartment",
    "Greater Kailash 1",
    "DLF One Midtown",
    "Shubham CGHS",
    "Dwarka Sector 8",
    "Uttam Nagar West",
    "Krishna Apartment",
    "Panchsheel Enclave",
    "DDA Indraprastha Apartment",
    "Vrundavan Society",
    "DLF Capital Greens 1 and 2",
    "Safdarjung Enclave",
    "Gulmohar Park",
    "DGS Apartment",
    "Tagore Garden",
    "Delhi Rajdhani Apartments",
    "Greater Kailash 2",
    "Rohini Sector 3",
    "Nehru Nagar",
    "Priyadarshini Vihar",
    "Himachal Apartment",
    "Uttam Nagar West",
    "Rohini Sector 23",
    "New Delhi",
    "Sheikh Sarai Phase 2",
    "Sheikh Sarai Phase 1",
    "Greater Kailash 1",
    "Skylark Apartment",
    "Arya Chittaranjan Park",
    "Yojana Vihar RWA",
    "Prashant Vihar",
    "Sri Durga Apartment",
    "Ashiana Apartment",
    "Mohan Garden",
    "DDA Flats Pocket 4",
    "Pahar Ganj",
    "Wazir Nagar",
    "Mehrauli New Delhi",
    "Mahavir Enclave Part 1",
    "Rajdhani Enclave",
    "Mehrauli",
    "Shubh Laxmi Apartment Sector 6 Dwarka",
    "Bijwasan",
    "Rohini",
    "H Block-Saket",
    "Tilak Marg",
    "Shankar Vihar",
    "Paryatan Vihar",
    "Palm Green",
    "DDA Flats",
    "Laxmi Nagar",
    "Paryatan Vihar",
    "Paryatan Vihar",
    "East Of Kailash",
    "DDA Dhruva Apartments",
    "Paschim Vihar Block B5 New Delhi",
    "Masjid Moth",
    "Uttam Nagar",
    "Paradise Apartment",
    "Dakshinpuri New Delhi",
    "Om Apartments",
    "Hargobind Enclave",
    "Pitampura",
    "Brahma Apartments",
    "DDA Sunveiw Apartments",
    "Madhuban Enclave",
    "Rajouri Garden",
    "DDA Flats Vasant Kunj",
    "Anand Niketan",
    "Malviya Nagar",
    "Safdarjung Development Area",
    "New Friends Colony",
    "Greater Kailash 2",
    "DDA Flats",
    "Preet Vihar",
    "Neeti Bagh",
    "Parmarth Apartment",
    "DLF One Midtown",
    "Chittaranjan Park",
    "Maharani Bagh",
    "Park Royal Apartments",
    "Chhattarpur Enclave",
    "Shiv Nagar",
    "Shahdara",
    "Pandav Nagar",
    "West Vinod Nagar",
    "Vasant Kunj",
    "Chhattarpur",
    "Himvarsha Apartment",
    "Rohini Sector 16",
    "New Rajendra Nagar",
    "New Delhi",
    "Raghubarpura",
    "Raghubarpura New Delhi",
    "Safdarjung Enclave",
    "Ram Nagar",
    "Panchsheel Vihar",
    "DDA Vivekananda Apartment",
    "Raja Garden New Delhi",
    "Gamri Village",
    "Anand Vihar",
    "DDA Flats Pocket E",
    "Dwarka Sector 8",
    "MK Residency",
    "Sainik Farm New Delhi",
    "Rohini Sector 21",
    "Kailash Colony",
    "Haji Colony",
    "RWA POCKET 1 JASOLA",
    "New Mahavir Nagar",
    "New Delhi",
    "Pitampura",
    "Uttam Nagar",
    "The Shabad Apartment",
    "Govindpuri Extension",
    "Private Builders Independent Floor",
    "Lado Sarai",
    "Mahalaxmi Apartment",
    "DDA Flats Sector B Pocket 5 & 6",
    "Mahavir Enclave",
    "Shivam Apartment",
    "Hari Nagar",
    "Shivalik Colony",
    "Rohini Sector 9",
    "Roshanpura",
    "Roshanpura",
    "Adarsh Apartment",
    "Empire Apartment",
    "Khirki extension",
    "Rani Bagh",
    "Chhattarpur Enclave Phase2",
    "Dwarka Sector 16",
    "Saboli New Delhi",
    "Mayfair Apartments",
    "DDA Flats Sarita Vihar",
    "Greater Kailash 1",
    "Promise Apartments",
    "Punjabi Bagh West",
    "Mandi",
    "Sarita Vihar",
    "Defence Colony",
    "Uttam Nagar New Delhi",
    "Rajokri New Delhi",
    "Rajokri New Delhi",
    "Garden Estate",
    "Amritpuri",
    "Janakpuri",
    "Sector 19B Dwarka",
    "Sarvodaya Enclave",
    "Janakpuri Block A3",
    "Paryavaran Complex",
    "Paschim Vihar",
    "New Friends Colony Floors",
    "Neb Sarai",
    "Rana Pratap Bagh",
    "Dwarka Sector 26",
    "DDA Flats Vasant Kunj",
    "Karawal Nagar West",
    "Mahavir Enclave",
    "Paschim Vihar",
    "Kanungo Apartments",
    "Rohini Sector 35",
    "Vasant Kunj Sector C",
    "Sewak Park",
    "Kailash hills",
    "Rajokri New Delhi",
    "Hilansh Apartments",
    "Harsukh Apartment",
    "Bhagwati Garden Extension",
    "Jama Masjid",
    "Geeta Colony",
    "Jangpura Extension",
    "Narela",
    "Krishna Nagar New Delhi",
    "Apna Ghar",
    "Rohini Sector 18",
    "DDA Devdoot Apartment",
    "Dwarka Sector 23",
    "Molarband Block F",
    "Chander Vihar - Mandawali",
    "Ranaji Enclave",
    "Ranaji Enclave",
    "Kailash Colony",
    "JVTS Gardens",
    "Nehru Enclave",
    "Bharat Nagar New Delhi",
    "DDA Pocket D",
    "Paschim Vihar",
    "East Of Kailash",
    "Sitapuri New Delhi",
    "Vasant Kunj Sector B",
    "Bindapur",
    "Tagore Garden",
    "Friends Colony New Delhi",
    "Samaj Kalyan Apartments",
    "Panchsheela Park New Delhi",
    "Mayur Vihar",
    "Janakpuri",
    "Rajpur Khurd Extension",
    "Dwarka Sector 23B",
    "DDA Atulya Apartment",
    "Vikaspuri",
    "Chattarpur Enclave",
    "Paryavaran Complex",
    "Naraina Vihar",
    "Krishna Nagar",
    "Chandni Chowk",
    "Sukh Sagar Apartment",
    "Project Gangotri Enclave",
    "Great India Apartment",
    "Malviya Nagar",
    "Highland Tower",
    "Rohini Sector 20",
    "East Of Kailash",
    "Surya Apartment",
    "New Mahavir Nagar",
    "Ambedkar Nagar New Delhi",
    "Mayur Vihar 1",
    "Bijwasan",
    "Rohini Sector 2",
    "Chander Vihar",
    "Pitampura",
    "Khajuri Khas New Delhi",
    "Ghonda Patti",
    "Paschimpuri",
    "Maurya Enclave",
    "Yojna Vihar",
    "Outram Lines",
    "Sanjay Enclave",
    "Sant Nagar",
    "Subhash Nagar",
    "Vaishali",
    "Krishna Nagar",
    "Bhagwati Garden Extension",
    "Safdarjung Enclave New Delhi",
    "Azadpur",
    "Sant Nagar Vishnu Garden",
    "Sant Nagar Vishnu Garden",
    "surajmal vihar Teacher colony Delhi New Delhi",
    "South Extension 2",
    "DDA Flats Pocket F",
    "Sarai Jullena",
    "Sarai Jullena",
    "Kewal Park",
    "Ashok Nagar",
    "Janakpuri",
    "Rohini Sector 11",
    "Sanjay Enclave",
    "Greater Kailash 1",
    "Mahavir Enclave",
    "Vishnu Garden",
    "South Extension 1",
    "RWA E Block",
    "Data ram park Najafgarh New Delhi",
    "Punjabi Bagh West",
    "Dilshad Garden",
    "Indraprastha Extension",
    "New Ashok Nagar",
    "Shastri Nagar",
    "Fancy Apartments",
    "Hari Nagar",
    "DDA LIG Apartment Dilshad Garden",
    "Kunj Vihar Apartment",
    "Greater Kailash 2",
    "Rohini Sector 4 New Delhi",
    "Satya Niketan",
    "Safdarjung Development Area",
    "Vikaspuri",
    "Yamuna Vihar",
    "Sagarpur New Delhi",
    "Lajpat Nagar 2",
    "Neethi Apartments",
    "Hauz Khas",
    "Dwarka",
    "Fatehpur Beri New Delhi",
    "DDA Flats Munirka",
    "Mahavir Enclave Part 1 New Delhi",
    "Sainik Enclave New Delhi",
    "Sainik Vihar",
    "Surajmal Vihar New Delhi",
    "Ram Dutt Enclave",
    "DDA DTC Colony",
    "Hauz Khas New Delhi",
    "Laxmi Nagar New Delhi",
    "Om Vihar",
    "Rohini Sector 21",
    "Sagarpur",
    "Savarkar Apartments",
    "Mansarover Garden",
    "DDA Golf Link Residency",
    "Rohini Sector 6",
    "Sainik Enclave",
    "New Friends Colony New Delhi",
    "Rohini Sector 17 New Delhi",
    "Kst Chattarpur Villas",
    "Rajouri Garden",
    "DDA Freedom Fighter Enclave",
    "Raja Puri",
    "Sarvodaya Enclave",
    "Sonia Vihar New Delhi",
    "Bhairav Bharti Apartment",
    "Uttam Nagar West",
    "SBI Apartment",
    "Maitri Apartments",
    "DDA Flats Sector 23",
    "Derawal Nagar",
    "Balbir Nagar",
    "Chittaranjan Park Block E",
    "Pushpanjali",
    "Reotech Builder Floors Sec 21",
    "DDA Pocket F",
    "Mohan Garden",
    "Rohini Sector 5",
    "Lajpat Nagar 2",
    "Sahid Bhagat Singh Apartment",
    "Prakriti Apartments",
    "DDA Flats Sarita Vihar",
    "Greater Kailash 3",
    "Anand Vihar",
    "Vishwakarma Colony",
    "Saraswati Garden",
    "Najafgarh New Delhi",
    "Rohini Sector 3",
    "Saraswati Garden",
    "Mori Gate New Delhi",
    "Dwarka Sector 10",
    "Kirti Nagar",
    "Mehrawali Apartment",
    "Lajpat Nagar III",
    "Model Town",
    "Punjabi Bagh East",
    "Harmony Apartment",
    "Rajouri Garden",
    "Luxury Floors by Mark Developers",
    "Gobind Apartment",
    "Sidharth Enclave",
    "Shakti Nagar",
    "Anand Vihar New Delhi",
    "Rohini Sector 7 New Delhi",
    "DDA Central Government Housing Complex",
    "Techer Colony",
    "Ashram",
    "Shahdara New Delhi",
    "Neelkanth Apartment",
    "DDA Freedom Fighter Enclave",
    "TARC Tripundra",
    "Satyam Apartment",
    "Keshav Puram",
    "Jangpura B",
    "Keshav Puram",
    "DLF Centre",
    "Private Colony",
    "Private Colony",
    "Nav Sanjivan",
    "Sree Badrinath Apartment",
    "Vivekanand Puri",
    "Vivekanand Puri",
    "Vivekanand Puri",
    "Tilak Marg",
    "Tilak Marg",
    "New Delhi",
    "Raj Nagar 2",
    "Jagriti Enclave",
    "Chittaranjan Park",
    "Mayur Vihar 1",
    "Jasola",
    "Aditi Apartment",
    "Tilak Nagar",
    "DDA Ekta Apartments",
    "Shivalik",
    "Om Vihar",
    "Kalka Apartments",
    "Dwarka",
    "JVTS Gardens",
    "Narela Sector A9",
    "Panchsheel Park",
    "Vikaspuri",
    "Mohan Garden",
    "Bhogal",
    "Aya Nagar Extension New Delhi",
    "Safdarjung",
    "Chittaranjan Park Block D",
    "Vinoba Puri",
    "Rajendra Place",
    "DDA Lig Flats",
    "Mansarovar garden",
    "Chittaranjan Park",
    "Gulmohar Enclave",
    "Vip Garden",
    "Skyom Apartment",
    "East Of Kailash Block D",
    "Khyala",
    "Sainik Farm New Delhi",
    "Kirti Nagar New Delhi",
    "Rani Bagh",
    "Shiva Enclave",
    "Palam",
    "Bank Vihar Apartments",
    "West End",
    "Rohini New Delhi",
    "DDA Shanti Kunj Apartment",
    "Chhattarpur",
    "Palm Green Apartment",
    "Model Town Phase 2",
    "Build Wick Iconic Homes",
    "Jagriti Enclave",
    "Rani Bagh New Delhi",
    "Vivek Vihar New Delhi",
    "New Delhi",
    "Rohini Sector 7",
    "DDA Azad Apartment",
    "Mehrauli",
    "Sundar Nagar",
    "West End New Delhi",
    "West Rohtash Nagar",
    "Dwarka Sector 3",
    "Malka Ganj",
    "Ramesh Nagar",
    "DDA Azad Apartment",
    "Vijay Enclave",
    "Gagan Vihar CGHS Ltd",
    "Daryaganj",
    "Rohini sec 11 New Delhi",
    "Aggarwal Builder Floors",
    "Dilshad Colony",
    "RWA Greater Kailash 1",
    "Khanpur Colony",
    "Shahdara",
    "Sultanpur New Delhi",
    "DDA LIG Flats Rohini",
    "Lajpat Nagar 2",
    "St Nagar Burari",
    "Mohan Garden",
    "Asian Games Village Complex",
    "Rwa GK 1",
    "New Friends Colony New Delhi",
    "Beri Wala Bagh-Hari Nagar",
    "Laxmi Nagar",
    "Vivek Vihar Phase 1 New Delhi",
    "Mandi",
    "Mayur Vihar",
    "Mahendra Park",
    "Aastha Kunj Apartments",
    "Nangloi Saiyed",
    "Laxmi Nagar",
    "Braham Puri",
    "Vikaspuri Extension Pocket A Part 1",
    "Chirag Enclave",
    "Green Park",
    "Vigyan Vihar",
    "Shahabad Mohamad Pur",
    "Kalkaji",
    "DDA Azad Apartment",
    "Vijay Park",
    "Meenakshi Garden",
    "Vijay Park New Delhi",
    "Young Aheria Apartment",
    "Malviya Nagar",
    "Adarsh Nagar Extension",
    "Kalkaji",
    "Vikaspuri Pocket DG2",
    "Sunder Vihar",
    "Kilokri",
    "DDA Gaurav Apartment",
    "Inderpuri",
    "Meera Bagh",
    "Laxmi Nagar",
    "Mayapuri",
    "Pahar Ganj New Delhi",
    "DDA Sanskriti Apartments Dwarka",
    "Ayodhya Enclave",
    "Jawahar Nagar",
    "DDA Flats Vasant Kunj",
    "Ashok Vihar Phase 1",
    "Vasundhara Enclave",
    "Anarkali Colony South",
    "Vinoba Puri",
    "Molarband",
    "Ja Nagar",
    "Vishal Enclave",
    "Vishal Enclave",
    "Vishal Enclave",
    "Karol Bagh New Delhi",
    "Guru Angad Nagar West",
    "Shastri Nagar",
    "Laiha Apartment",
    "Uday Park",
    "Shaman Apartments",
    "Defence colony Villas",
    "Vasant Kunj",
    "Manglam Place Rohini New Delhi",
    "Govindpuri Main",
    "Yojna Vihar",
    "Sangam Vihar New Delhi",
    "Premium Builder Floors",
    "Harit Vihar",
    "Kotla Mubarakpur",
    "Kalkaji",
    "Lajpat Nagar 1",
    "Shalimar Bagh West BE Block",
    "Lovely Apartments",
    "Neeti Bagh",
    "Bhajanpura",
    "Batukji Apartment",
    "Krishna Nagar-Safdarjung Enclave",
    "Bhai Parmanand Colony",
    "Govindpuri Ma New Delhi",
    "Inderpuri",
    "Yamuna Vihar New Delhi",
    "Savitri Nagar Village",
    "DS 19",
    "New Ashok Nagar",
    "DDA Ekta Apartment",
    "Mahavir Enclave Part 1",
    "Sudarshan Park",
    "Najafgarh New Delhi",
    "Chhattarpur Enclave Phase2",
    "DDA EWS Housing Project",
    "Manavsthali Apartment",
    "Rama Krishna Apartments",
    "Kakrola",
    "CA Block Shalimar Bagh",
    "Punjabi Bagh Extension",
    "Alaknanda",
    "Anarkali Colony",
    "Shyam Vihar 1 Najafgarh New Delhi",
    "Mansarovar garden New Delhi",
    "Brahmpuri New Delhi",
    "Sukhdev Vihar",
    "Uttam Nagar",
    "Pawittra Apartment",
    "Shivaji Nagar",
    "Jangpura Extension",
    "Krishna Nagar",
    "Indraprastha Extension",
    "Dwarka Mor",
    "Jaffarpur Kalan New Delhi",
    "Jamia Nagar",
    "Rani Bagh",
    "DDA Pocket JK",
    "Tri Nagar New Delhi",
    "Khanpur",
    "Pratap Nagar New Delhi",
    "Kanwar Singh Nagar",
    "Sultanpur",
    "Gandhi Vihar",
    "Shahdara New Delhi",
    "Neb Sarai",
    "Fyaz Ganj",
    "Jhangir Puri",
    "Chhattarpur",
    "Jasola Pocket 12 LIG Flats",
    "Kamla Nagar",
    "Mandawali",
    "DDA LIG Flats",
    "Ramesh Nagar",
    "West Rohtash Nagar",
    "Sadbhawana Apartment",
    "AG1 Pocket Vikaspuri",
    "Jaitpur New Delhi",
    "DDA Nilgiri Apartment",
    "Naraina Vihar",
    "Chhattarpur",
    "Chitrakut Apartment",
    "Rajdhani Nikunj Apartment Patparganj",
    "Rohini New Delhi",
    "City Apartment",
    "Basai Darapur",
    "Yojana Vihar RWA",
    "RWA Malviya Nagar",
    "CGHS Kirti Apartments",
    "New Delhi",
    "Burari",
    "Dakshini Pitampura",
    "Dwarka Sector 15",
    "Rohini Sector 24",
    "Vasant Apartments",
    "Unity the Amaryllis",
    "DDA LIG Flats",
    "Pankha Road",
    "Mansarover Garden",
    "Dwarka Sector 14",
    "Vikash Nagar New Delhi",
    "Uttam Nagar West New Delhi",
    "the professional New Delhi",
    "Sonia Vihar New Delhi",
    "Mahavir Enclave New Delhi",
    "Vikaspuri",
    "Best Residency",
    "Kapashera Apartment",
    "Shahdara New Delhi",
    "CC Colony",
    "Dwarka",
    "Delhi State NEF CGHS Limited",
    "DDA Flats Munirka",
    "Sainik Nagar",
    "Geeta Colony",
    "Firozeshah Road",
    "Palam Colony",
    "Vikaspuri Block C New Delhi",
    "Chitra Vihar",
    "Dwarka Sector 19B",
    "DLF Capital Greens 1 and 2",
    "Sunlight Colony Phase 2",
    "Rohini",
    "Paschim Vihar New Delhi",
    "Srinagar Garden",
    "DDA Flats Sector E Pocket 2",
    "Doctors Apartment",
    "Patel Nagar East",
    "Sriniwaspuri Extension",
    "Swati Apartments",
    "Sukhdev Vihar",
    "Paschim Vihar Block A2",
    "Ganesh Nagar",
    "Radhey Shyam Park",
    "Uttam Nagar West New Delhi",
    "Kewal Park",
    "Saket",
    "DDA LIG Flat",
    "Dwarka Sector 14",
    "Palam Colony",
    "Kishangarh Village",
    "Gulistan Apartment",
    "Ashram",
    "Parijat Apartment",
    "Chhattarpur New Delhi",
    "Sukh Sagar Apartment",
    "DDA Flats Vasant Kunj",
    "DDA Flats Pocket 1",
    "New Rohtak Road",
    "Green Park Extension",
    "Shadipur",
    "Tri Nagar",
    "Shahpur Jat",
    "Shahpur Jat",
    "Poorvi Shalimar Bagh",
    "Shastri Nagar Block B",
    "Virender Nagar",
    "Poorvi Shalimar Bagh",
    "Vishrantika Apartments",
    "Budh Vihar Phase 1",
    "Sitapuri",
    "Mahavir Enclave Part 1",
    "Hauz Khas Enclave",
    "Soami Nagar",
    "Patel Nagar East",
    "moedl basti filmistan New Delhi",
    "LIC Colony",
    "DDA Flat AC Block",
    "Tarun Vihar Apartment",
    "Uttam Nagar New Delhi",
    "Vikram Vihar",
    "Veena Apartment",
    "Sant Nagar New Delhi",
    "Kalkaji New Delhi",
    "DDA Flats Sector E Pocket 2",
    "Rohini Sector 22",
    "Burari New Delhi",
    "Dwarka Sector 15",
    "Jangpura Extension",
    "Kishan Ganj New Delhi",
    "nawada bazar Najafgarh New Delhi",
    "Rama Park",
    "Govindpuri Main",
    "Mehrauli",
    "DDA Shikha Apartment",
    "New Chandrawal",
    "Anarkali Colony",
    "Soami Nagar",
    "Soami Nagar New Delhi",
    "Tagore Park",
    "West Vinod Nagar New Delhi",
    "Sagarpur West",
    "Srinagar Garden",
    "Srinagar Garden",
    "Srinagar Garden",
    "Z Block Prem Nagar New Delhi",
    "Khirki extension",
    "Burari Santan Nagar",
    "Doctors Apartment",
    "Rohini Sector 24",
    "Shiv Vihar",
    "Kanhaiya Nagar",
    "govind pura New Delhi",
    "Uttam Nagar West New Delhi",
    "Greater Kailash Builder Floors",
    "Bhajanpura New Delhi",
    "Shalimar bagh",
    "Ganesh Nagar",
    "Shree Krishna Residency",
    "Ashok Vihar",
    "Rohini Sector 25",
    "DDA Pink Apartments",
    "West End",
    "Lawrence Road",
    "Devli",
    "Timarpur New Delhi",
    "Najafgarh New Delhi",
    "Pacific Apartment",
    "Mianwali Nagar",
    "Mianwali Nagar",
    "Mianwali Nagar",
    "Rohini Sector 22",
    "Kaveri Apartment",
    "Sheikh Sarai Phase 2",
    "Mangolpuri",
    "Punjabi Bagh West New Delhi",
    "Milan Vihar",
    "Sangam Vihar",
    "Milap Nagar",
    "Pushpanjali Apartments",
    "Saraswati Vihar",
    "Pushpanjali Apartments",
    "Pushpanjali Apartments",
    "Pushpanjali Apartments",
    "Hari Enclave",
    "Ramakrishna Puram New Delhi",
    "Malka Ganj",
    "Shashi Garden",
    "Mithapur New Delhi",
    "Model Town Phase 2",
    "IIT Engineers Apartments",
    "Lajpat Nagar 1",
    "Rohini Sector 26",
    "JVTS Gardens",
    "Vishwakarma Colony",
    "Sudarshan Park",
    "Rithala",
    "Bharat Nagar",
    "Mayur Vihar 1",
    "Antariksha Apartments",
    "Sainik Farm New Delhi",
    "Air India Employees Apartment",
    "Deshbandhu Apartments",
    "Prodyogiki Apartments x",
    "Krishna Nagar Extension",
    "Appu Enclave Apartment",
    "Appu Enclave Apartment",
    "Munirka Apartments",
    "Prayag Apartments",
  ],

  Faridabad: [
    "RPS Savana",
    "Aashirwad Homes",
    "Sector 86",
    "Emerald Heights",
    "RPS Auria Residences",
    "Greenfield Colony",
    "BPTP Discovery Park",
    "Sector 85",
    "Adore Happy Homes Exclusive phase 2",
    "Sector 88",
    "Badarpur Metro Station",
    "Tirka Colony",
    "Housing Board Duplex",
    "Housing Board Duplex",
    "SRS Pearl",
    "Mujesar Village",
    "Omex Green Valley",
    "Era Divine Court",
    "BPTP Park 81",
    "Sector 31",
    "Sector 28",
    "Adore Legend",
    "KLJ Greens",
    "Sector 83",
    "Sector 77",
    "Puri Pratham",
    "Mulberry County",
    "Bptp Eden Estate Sector 81",
    "Sector 21C",
    "Faridabad",
    "Ashoka Enclave Part 2",
    "Faridabad",
    "BPTP Park Elite Premium Villas",
    "Omaxe Heights",
    "BPTP Pride",
    "Greenfield Colony",
    "Sector 31",
    "SGM Nagar Faridabad",
    "Faridabad",
    "Omaxe Heights",
    "Sanjay Colony",
    "Sector 15",
    "Emerald Heights",
    "BPTP Princess Park",
    "Greenfields Colony Block A",
    "Sector 65",
    "Nehru Ground",
    "Sector 81",
    "Advitya Homes",
    "BPTP Park Central",
    "Mansha Luxury Floors",
    "Sector 21D",
    "Bptp District",
    "BSNL Apartments",
    "Woodbury Tower",
    "BPTP Pride",
    "Sector 75 Faridabad",
    "Sector 76",
    "Ibiza Town",
    "Sector 49",
    "Sector 15",
    "Sector 16",
    "Sector 16",
    "sector 10 HBC Faridabad",
    "Sector 37",
    "Sarvome Shree Homes",
    "Nice Group Housing",
    "Agrasa Aagman 2",
    "Eros Belvedere Tower",
    "Gupta Ji Floors",
    "Ozone Park Apartments",
    "Mahesh Apartment",
    "New Industrial Township 3",
    "IFCI Park View Apartments",
    "SRS Pearl Heights",
    "Ansal Royal Heritage",
    "SRS Royal Hills Phase 1",
    "Omaxe The Forest SPA",
    "Sector 21A",
    "Charmwood Village",
    "Sector 21C",
    "sai park Apartment sector 87",
    "Omaxe New Heights",
    "Sector 85",
    "Advitya Homes",
    "SRS Royal Hills",
    "Sector 22",
    "Sector 88",
    "Sector 14",
    "Indraprastha Apartments 1",
    "Sector 11",
    "Sector 21",
    "Sector 21",
    "Sector 21",
    "Anmol",
    "Sector 30",
    "Sainik Colony",
    "Sanjay Enclave Colony Faridabad",
    "Sector 41",
    "Sector 41",
    "Sector 41",
    "Sector 55 Faridabad",
    "Gokul Apartments",
    "Sector 55 Faridabad",
    "Piyush Heights",
    "Sector 28",
    "Sector 30",
    "Sector 24",
    "Anmol",
    "Sector 7",
    "New Industrial Township 1",
    "SRS Residency",
    "Sector 22",
    "Sector 28",
    "Urban One",
    "Sector 89",
    "Sector 62 Faridabad",
    "Floridaa",
    "Amolik Residency",
    "Ballabhgarh Sector 1",
    "BPTP Park Elite Floors",
    "Sector 21D",
    "New Industrial Township 3",
    "Conscient Habitat 78",
    "Ansal Royal Heritage",
    "Greenfield Colony",
    "Sector 45",
    "Indarparstha Colony Part 3",
  ],

  Ghaziabad: [
    "Siddhartha Vihar",
    "Rajendra Nagar",
    "Indirapuram",
    "Shakti Khand",
    "The Golden Gate",
    "Neeti Khand 2",
    "Uninav Bliss",
    "Vasundhara",
    "DigiTown",
    "Aditya White Cottage",
    "Mahagun Mansion 1 and 2",
    "KW Srishti",
    "Aditya World City",
    "Kavi Nagar",
    "Uninav Eden",
    "Uninav Eden",
    "Mahagun Puram",
    "ATS Advantage",
    "Nandini The Vasundhara Grand",
    "Raj Garden City",
    "Raj Garden City",
    "RWA DLF Colony",
    "Chhapraula Ghaziabad",
    "Lal Kuan Ghaziabad",
    "Sadarpur",
    "T Homes",
    "Oxy Homez",
    "Vasundhara Sector 9",
    "Vaishali Sector 5",
    "Ghaziabad Road",
    "Krishna Nagar",
    "Saubhagya Puram",
    "Migsun Roof",
    "Sector 12 Pratap Vihar",
    "Gyan Khand 4",
    "Gyan Khand 4",
    "Judges Enclave",
    "Niti Khand-Indirapuram",
    "Pandav Nagar",
    "Ansal East End",
    "Radha Kunj",
    "Radha Kunj",
    "Lal Kuan",
    "Vaishali Sector 4",
    "Ajnara Integrity",
    "Swarn Residency",
    "Neeti Khand 1",
    "Rise Organic Ghar",
    "Mahagun Mascot",
    "Vasundhara Sector 3",
    "Amrapali Village",
    "Raj Nagar",
    "Dlf Dilshad Plaza",
    "Vaishali Sector 2",
    "KDP Grand Savana",
    "Neeti Khand 1",
    "Shakti khand 1",
    "Raispur",
    "Raispur Ghaziabad",
    "Bankey Bihari Sharnam",
    "Raispur Ghaziabad",
    "Rajendra Nagar Sector 5",
    "Palm Resort",
    "Indirapuram",
    "Aditya Mega City",
    "Vardaan Apartments",
    "Paramount Symphony",
    "Sector 23 Sanjay Nagar Ghaziabad",
    "SG Grand",
    "Gyan Khand 1",
    "Gaur Heights",
    "Mahindra Enclave",
    "Wave City",
    "Sector 12 Pratap Vihar",
    "Ghaziabad",
    "Jaipuria Sunrise Greens",
    "Saviour Greenisle",
    "Panchsheel Primrose",
    "Vandana Apartment",
    "Paramount Mapple",
    "Vaishali Sector 6",
    "Rajnagar Residency",
    "Vaishali",
    "Ram Prastha",
    "Mahagun Mascot",
    "Kaushambi",
    "Prem enclave",
    "Landcraft Golf Links PH 2",
    "Shakti Khand 3",
    "Lal Quarter Ghaziabad Ghaziabad",
    "Ghaziabad",
    "Crossing Republic GH 7",
    "Ghaziabad",
    "Vaishali Sector 5",
    "Palm Resort",
    "Indirapuram Ghaziabad",
    "Rajendra Nagar Sector 3",
    "Turab Nagar",
    "Om Sai Garden",
    "Gaur Green City",
    "Neeti Khand 1",
    "ATS Advantage",
    "Vaishali Sector 4",
    "Jalalpur Ghaziabad",
    "Savy Ville De",
    "Diya Green City",
    "Vaishali",
    "Panchsheel Wellington",
    "Govindpuram Ghaziabad",
    "Vaishali Sector 3",
    "DLF Ankur Vihar",
    "Vasundhara",
    "Dream Homes",
    "Proview Shalimar City Phase I",
    "Lajpat Nagar Sector 4",
    "Gaur Cascades",
    "Gaurs Siddhartham",
    "GRC Greenwoods",
    "Ramprastha Greens Pearl Court",
    "ATS Advantage",
    "Neeti Khand 1",
    "Shalimar garden",
    "Mahagun Mascot",
    "SG Impression Plus",
    "Bharat City 2",
    "Green View Apartment",
    "Niti Khand-Indirapuram",
    "Sector 23 Sanjay Nagar Ghaziabad",
    "Vaishali",
    "R V Homes",
    "Balaji Enclave",
    "Chiranjiv Vihar",
    "DLF Ankur Vihar",
    "Vaishali Sector 3",
    "Metro Suites Glitz",
    "Eutopia",
    "Raj Nagar Extension Ghaziabad",
    "Aakash Kunj Apartment",
    "Gyan Khand 3",
    "Migsun Kiaan",
    "Parsvnath Regalia",
    "Vaishali Sector 4",
    "Sahibabad",
    "NH 24",
    "Indraprastha Flat",
    "Shri Balaji Residency",
    "Rampuri",
    "Sahibabad Industrial Area Site 4",
    "SVP Gulmohur Residency",
    "Ram Nagar Ghaziabad",
    "Rajendra Nagar",
    "Wave Executive Floors",
    "Sarvodaya Nagar",
    "Lohia Nagar Ghaziabad",
    "Ghaziabad",
    "Banke Bihari Kunj",
    "Vasundhara Sector 17",
    "Modinagar Ghaziabad",
    "Panchsheel Primrose",
    "Lal Kuan",
    "Vasundhara",
    "Gaurs Plaza",
    "Bharat City",
    "Euro Apartment RWA",
    "ATS Advantage",
    "Mahagun Sarovar Portico",
    "Shipra Krishna Vista",
    "Rajendra Nagar Sector 3",
    "Indirapuram",
    "vasundhra ghaziabad Ghaziabad",
    "Krishna Apra Gardens",
    "Rishabh Cloud 9 Towers Vaishali",
    "Ansal East End",
    "Ramprastha Greens",
    "Shipra Sun City",
    "Kamna Apartments",
    "Mahagun Mansion 1 and 2",
    "Gyan Khand 1",
    "ATS Advantage Phase 2",
    "Pragya Kunj Apartments",
    "Windsor and Nova Society",
    "Indirapuram",
    "Vrindavan Green",
    "Shyam Park Extension",
    "DLF Ankur Vihar",
    "Vasundhara Sector 2B",
    "Orange County",
    "Gyan Khand 3",
    "Niti Khand-Indirapuram",
    "Raj Nagar Extension",
    "SG Shikhar Height",
    "SPS Residency",
    "Rajnagar Residency",
    "Shakti Khand 2",
    "Vasundhara Sector 14",
    "NH 24",
    "Shalimar City",
    "Loni Road Ma Durga Puri",
    "Avantika Colony",
    "Vasundhara Sector 17",
    "Judges Enclave",
    "Saviour Park",
    "Gaur Homes",
    "Shalimar garden",
    "GDA Block C",
    "Madhuban Bapudham",
    "Saya Gold Avenue",
    "Devika Apartments",
    "Vaishnavi Kunj",
    "Shastri Nagar",
    "Highend Paradise",
    "Shalimar garden",
    "Vaishali Sector 1",
    "Surya Heights",
    "Vasu Fortune Residency",
    "Skytech Evergreen Homes",
    "Dwarika 25",
    "Abhay Khand 3",
    "Chander Nagar",
    "Supertech Livingstone",
    "Vaishali Sector 6",
    "Palm Sunrise",
    "Patel Nagar 1 Ghaziabad",
    "Aditya City Apartments",
    "Ramprastha Colony",
    "Nyay Khand 1",
    "Amrapali Empire",
    "Govindpuram Ghaziabad",
    "Brahmaputra Enclave",
    "NH 24",
    "GDA Block P",
    "ATS Advantage Phase 2",
    "ATS Advantage Phase 2",
    "ATS Advantage Phase 2",
    "Mahalakshmi Buildcon",
    "Siddhartha Vihar",
    "Dev Heights",
    "Bhopura",
    "ADITYA GARDEN CITY",
    "ADITYA GARDEN CITY",
    "New Panchwati Colony",
    "Shipra Riviera",
    "Bahrampur",
    "Nilaya Greens",
    "Oxy Homez",
    "KDP MGI Gharaunda",
    "Vidhayak Colony",
    "Sanjay Nagar",
    "Naya Khand",
    "Shalimar Garden Extension 1",
    "Pratap Vihar",
    "Wave Hitech City",
    "Vaishali Sector 2",
    "Pratap Vihar Ghaziabad",
    "Royce Vaishali",
    "Patel Nagar 2 Ghaziabad",
    "Jaipuria Sunrise Greens",
    "Gaur Green Vista",
    "Devika Skypers",
    "Ahinsa Khand-2",
    "Aditya Urban Homes",
    "Siddhartha Vihar",
    "Charms Castle",
    "Balaji Enclave",
    "Gyan Khand 2",
    "Nai Basti Dundahera",
    "RISHABH PARADISE",
    "RISHABH PARADISE",
    "RISHABH PARADISE",
    "RISHABH PARADISE",
    "Civitech Florencia",
    "Civitech Florencia",
    "Bhopura",
    "Leo Apartment",
    "Shalimar Garden Extension 1",
    "ADITYA GARDEN CITY",
    "Dlf Dilshad Extension",
    "Media Enclave",
    "Loni",
    "Sahibabad",
    "Bharat City",
    "Raj Nagar Extension",
    "Chipiyana Buzurg Ghaziabad",
    "Chhapraula",
    "RM Block",
    "Janakpuri",
    "Supertech Livingstone",
    "Orange County",
    "Kaushambi",
    "Gaur Ganga 2",
    "Mahaluxmi Homz",
    "Signature Residency",
    "Morta",
    "Mehak Jeevan",
    "Mehak Jeevan",
    "Sihani Gate",
    "Sihani Gate",
    "Avantika Colony",
    "Vaibhav Khand",
    "Shaheed Nagar",
    "Sudha Sarovar Apartment",
    "Rail Kunj Apartments",
    "Vasundhara Sector 3",
    "Patel Nagar",
    "Shatabdipuram",
    "Raj Nagar Extension",
    "Oxirich Avenue",
    "Shipra Sun City",
    "Unione Residency",
    "Saya Gold Avenue",
    "Niti Khand-Indirapuram",
    "Nyay Khand 1",
    "Kavi Nagar",
    "Surya Kanishk Tower",
    "NBCC Town",
    "Angel Mercury",
    "Surya Deep Apartment",
    "MKS La Royale",
    "The Royal Cliff",
    "Mahagun Estates III",
    "Wave Veridia",
    "Sihani Gate",
    "Diya Green City",
    "Dundahera",
    "Ansal Aquapolis",
    "Ansal Aquapolis",
    "Dundahera",
    "Vaishali Sector 9",
    "Sahibabad Ghaziabad",
    "Mahagun Mosaic",
    "Unione Residency",
    "La Gracia",
    "Shakti Khand II",
    "Shakti Khand II",
    "Shakti Khand II",
    "Vaishali Sector 2 Ghaziabad",
    "Sahibabad",
    "Raj Nagar Ghaziabad",
    "Saya Gold Avenue",
    "Jaipuria Apartment",
    "Kailashpuram",
    "Rampuri",
    "Marium Nagar",
    "Amrapali Empire",
  ],

  Noida: [
    "CRC Joyous",
    "Nirala Aspire Phase 4",
    "Antriksh Grand View",
    "Paramount Emotions",
    "Capital Athena",
    "Jaypee Greens Knights Court",
    "Knowledge Park 3",
    "Godrej Tropical Isle",
    "Panchsheel Greens 2",
    "Noida Extension Block A Noida",
    "Express Astra",
    "Jaypee Greens Crescent Court",
    "Panchsheel Pratishtha",
    "CRC Joyous",
    "Amrapali Smart City",
    "Sector MU 2",
    "Mahagun Manorialle",
    "Express Astra Phase 2",
    "Mahagun Manorialle",
    "ACE Divino",
    "Logix Blossom County",
    "Trident Embassy Reso",
    "Amrapali Sapphire",
    "The Islands by Gaurs",
    "Antriksh Nature",
    "Gaur City 7th Avenue",
    "East Avenue",
    "Apex Athena",
    "Cassia Sigma",
    "Aba Cherry County",
    "Samridhi Luxuriya Avenue",
    "Splendour",
    "County 107",
    "Sector 15 Block A",
    "Prateek Wisteria",
    "Pan Oasis",
    "Spring Elmas",
    "CRC Joyous",
    "Supertech Ecociti",
    "Paramount Golfforeste",
    "Krystal Homes",
    "ATS Greens Village",
    "11th Avenue Gaur City 2",
    "Sector 51 Noida",
    "Amrapali Silicon City",
    "Sector 75",
    "Nirala Greenshire",
    "Fusion The Brook",
    "Zeta 1",
    "Spring Homes",
    "Ivy County",
    "Prateek Laurel",
    "Tw Celestial",
    "ACE City",
    "Sector 41",
    "AIG Royal",
    "Gaur City 2",
    "Sector 62",
    "RWA Jalvayu Vihar",
    "Jaypee Greens Kalypso Court",
    "RR Homes",
    "ATS Pious Hideaways",
    "Galaxy North Avenue",
    "Sector 1",
    "Gaur City 1st Avenue",
    "Vijayant Enclave",
    "Ansal Plaza-Gr. Noida",
    "Beta 2 Block G",
    "Paramount Floraville",
    "Aba Cherry County",
    "Radicon Vedantam Emporio",
    "RWA Sector 39",
    "ACE Divino",
    "Trident Embassy Reso",
    "Sikka Kimantra Greens",
    "Gamma 1 Block A",
    "Gamma 1 Block C",
    "11th Avenue Gaur City 2",
    "Aastha Greens",
    "ATS Green Paradiso",
    "Gaur City 2 Sanskriti Vihar",
    "NCR Monarch and Crown",
    "Sector 44",
    "Gamma 2 Block J Greater Noida",
    "Khairpur Gurjar",
    "Amrapali Princely Estate",
    "Nimbus Express Park View 2",
    "Supertech Czar Suites",
    "Paras Seasons",
    "Phi 3 Greater Noida",
    "Phi 3 Greater Noida",
    "Pocket 4 Phi 2",
    "Pocket 4 Phi 2",
    "Samridhi Grand Avenue",
    "The Hyde Park",
    "Griha Pravesh",
    "Gamma 1 Block C",
    "Sikka Kaamna Greens",
    "Jaypee Greens Imperial Court",
    "Greater Noida West",
    "Nirala Greenshire",
    "Stellar Sigma",
    "Jaypee Aman",
    "Sector 1",
    "UPSIDC Site C Block E Greater Noida",
    "UPSIDC Site C Block G",
    "Omaxe Grandwoods",
    "Panchsheel Pratishtha",
    "Aims Green Avenue",
    "Uppal Plumeria Garden Estate",
    "Cleo County",
    "Bhanauta Greater Noida",
    "Mahagun Mantra 2",
    "County 107",
    "Mahagun Mezzaria",
    "Chorosia Estate",
    "Chorosia Estate",
    "Stellar Sigma",
    "Saya Zion",
    "Paras Tierea",
    "Noida Extention",
    "Gaur City Mall",
    "Gulistanpur",
    "Ajnara Daffodil",
    "UPSIDC Site C Block E",
    "Vijayant Enclave",
    "Urbtech Xaviers",
    "Sector MU 2",
    "Sector 49 Block A",
    "Galaxy North Avenue 2",
    "Sector 113",
    "Sikka Karnam Greens",
    "Sector 1 Greater Noida",
    "Sector 46 Block A Noida",
    "Sunworld Vanalika",
    "Jaypee Greens Krescent Homes",
    "Jaypee Greens Krescent Homes",
    "VVIP Homes",
    "Supertech The Romano",
    "RWA Sector 61",
    "Sector 1 Greater Noida West",
    "Noida Extension",
    "Hawelia Valenova Park",
    "Hawelia Valenova Park",
    "Noida",
    "JM Florence",
    "Trikuta Hills",
    "Galaxy North Avenue",
    "Eldeco Utopia",
    "Sector-37",
    "Noida",
    "Arun Vihar",
    "Purvanchal Royal City II",
    "Chi 3",
    "Sector XU 1 Greater Noida",
    "3C Lotus Boulevard",
    "Delta 3 Block M Greater Noida",
    "Ajnara Homes",
    "Jaypee Kosmos",
    "Gamma 1 Block E",
    "Gamma 1 Block E",
    "Gamma 1 Block E",
    "Gamma 1 Block E",
    "Samridhi Daksh Avenue",
    "Greater Noida",
    "Purvanchal Silver City 2",
    "Phi 3 Noida",
    "Sector 47",
    "Amrapali Leisure Park",
    "Paramount Golfmart",
    "Sector 75",
    "Iec White House",
    "Exotica Fresco",
    "Jaypee Greens Kalypso Court",
    "Panchsheel Pinnacle Green",
    "ATS Pristine",
    "Supertech Eco Village 1",
    "Gaur City 2 12th Avenue",
    "Gamma 1 Greater Noida",
    "Designarch eHomes",
    "Sector 31",
    "Kaveri City Centre",
    "Saya Zion",
    "Amrapali Silicon City",
    "XU 3 Greater Noida",
    "Sector-4",
    "SKA Orion",
    "Greenarch Retail Shops",
    "Supertech Supernova",
    "Gaur City 2",
    "Beta 1 Greater Noida",
    "Sector XU 1",
    "Prateek Wisteria",
    "Noida Express Way",
    "Pigeon Spring Meadows",
    "3C Lotus Panache",
    "Golf City",
    "Greater Noida",
    "Amrapali Dream Valley",
    "ATS Homekraft Happy Trails",
    "Sector-PI",
    "Sector 15",
    "Today Ridge Residency",
    "Sector 108",
    "Sector 26 Block C",
    "Gaur Atulyam",
    "Mahagun Mantra 2",
    "Great Value Sharanam",
    "Bironda",
    "Sector 20 Noida",
    "Sector 20 Noida",
    "Lotus Boulevard",
    "Venetia Heights",
    "White Orchid",
    "Sector 70 Noida",
    "Panchachuli Apartments",
    "Gaur 2nd Parkview",
    "ATS Nobility",
    "Amrapali Silicon City",
    "Sector 41 Block J",
    "Migsun Twiinz",
    "Supertech Eco Village",
    "Supertech Supernova",
    "ATS One Hamlet",
    "Arun Vihar",
    "Parx Laureate",
    "Beta 1 Block E Greater Noida",
    "Mahagun Moderne",
    "Sector 117",
    "Noida",
    "Supertech Emerald Court",
    "Greater Noida",
    "Rise Resort Residences",
    "Sector 78",
    "Sector 61",
    "Parsvnath Residency",
    "Gautam Budh Nagar",
    "CRC Sublimis",
    "Sector 94",
    "Noida Extension",
    "Sector 44",
    "Sector 71",
    "Dhawalgiri Apartments",
    "Paramount Golf Foreste",
    "Sector P4 Greater Noida",
    "Eldeco Aamantran",
    "Gaur Yamuna City",
    "Prideville",
    "Gulshan Botnia",
    "Le Solitairian",
    "Nirala Aspire",
    "Noida Extention",
    "Gaur Saundaryam",
    "Salarpur",
    "Amrapali Green Valley",
    "Sigma 4 Greater Noida",
    "Sector 15",
    "Gaur City 16th Avenue",
    "Sector 62",
    "Sector 15",
    "Sector 15A",
    "Sector 15A",
    "Sector 17",
    "Noida Royale City",
    "Mahagun Morpheus",
    "Sector 137",
    "Sector 17 Noida",
    "Ajnara Homes",
    "Noida Royale City",
    "Sector 20",
    "Sector 20 Noida",
    "Sector 117",
    "Amrapali Silicon City",
    "Beta 2 Block I Greater Noida",
    "Eldeco Residency Greens",
    "Sector 118 Noida",
    "ATS Green Paradiso",
    "Sector 52 Noida",
    "Shatabdi Vihar",
    "Shatabdi Vihar",
    "Shatabdi Vihar",
    "Grand Ajnara Heritage",
    "ACE Divino",
    "CGEWHO Phase 1",
    "Nirala Estate Phase 2",
    "Godrej Golf Links",
    "Arihant Arden",
    "Vihaan Vista",
    "Gaur City 2 Sanskriti Vihar",
    "Nirala Estate Phase 1",
    "Greater Noida West",
    "Shatabdi Rail Vihar",
    "Delta 1 Greater Noida",
    "ADITYA CELEBRITY HOMES",
    "Shri Radha Sky Gardens",
    "Sector 120",
    "Telecom City Door Sanchar Sehkari Awas Samiti Limited",
    "Mahagun Mezzaria",
    "Jaypee Aman",
    "Panchsheel Greens",
    "Godrej Woods",
    "Noida",
    "Golf Gardenia",
    "RWA Sector 122",
    "Paramount Emotions",
    "JM Florence",
    "Fusion The Brook",
    "Wave Trucia",
    "Sigma 3 Greater Noida",
    "Paramount Golfforeste Premium Apartments",
    "Supertech Capetown",
    "Irish Pearls",
    "Sector 52 RWA",
    "Sector 135",
    "ACE Golfshire",
    "ATS Le Grandiose",
    "Wave Amore",
    "Panchsheel Greens",
    "Amarpali Group",
    "Ajnara Le Garden",
    "Khora Colony",
    "Aditya Urban Casa",
    "Neelkanth Apartments",
    "The Islands by Gaurs",
    "Pimpri Chinchwad",
    "Omaxe Forest Spa",
    "Vijayant Enclave",
    "East Avenue",
    "Ace Platinum",
    "Godrej Woods",
    "Panchsheel Greens Mart",
    "Noida Extension Noida",
    "UGCC Burgundy",
    "Sector 53 Block A",
    "P block sector 12 Noida",
    "Mahagun Manorialle",
    "Sector 92 Noida",
    "Supertech ORB Noida",
    "Supertech North Eye",
    "Stellar Sigma Apartments",
    "Sethi Max Royal",
    "Royal Garden Estate",
    "Sector 33 Block C Noida",
    "Sector 26 Noida",
    "Sector 73",
    "Logix Blossom Greens",
    "Ratan Pearls",
    "Assotech Springfields",
    "Assotech Springfields",
    "Amrapali Leisure Valley",
    "Godrej Woods",
    "ATS Greens 2",
    "Migsun Twiinz",
    "Sector 61 Block D",
    "Sector 55 RWA",
    "Shahberi",
    "Sector 51 Block B Noida",
    "Himalaya Pride",
    "Chi 5",
    "Sector 12 Block C Noida",
    "Gulmohar Estate",
    "Panchsheel Greens 2",
    "Victoryone Amara",
    "Sector 2 Block A",
    "Sukh Sagar Apartment",
    "Alpha 2 Greater Noida",
    "Ajnara Homes",
    "Migsun Ultimo",
    "ATS green 1",
    "ATS green 1",
    "Yamuna Expressway",
    "Imperia Residency",
    "Sector 22",
    "Sector 22 Block B Noida",
    "Jaypee Greens Moon Court",
    "Mayfair Residency",
    "Mayfair Residency",
    "Purvanchal Royal City",
    "Sector 25",
    "RWA Jalvayu Vihar",
    "Oasis Grandstand",
    "3C Lotus Panache",
    "Supertech Eco Village 1",
    "ACE Divino",
    "Sector XU 3 Greater Noida",
    "Sector 27 Noida",
    "Yamuna Enclave",
    "Varun Enclave",
    "Noida Authority Plots",
    "Sector 28",
    "Amrapali Eden Park",
    "gaur City 2 16th Avenue",
    "Sector 30 RWA",
    "Sector 30",
    "Panchsheel Greens Mart",
    "Cgewho Kendriya Vihar 2Â ",
    "Sector 30",
    "Jaypee Greens Kallisto Townhomes",
    "Supertech Supernova Spira Residences",
    "ATS Le Grandiose",
    "Sector-37 Greater Noida",
    "Gaur City 2 White Orchid",
    "Lotus 300",
    "Thee Halt Express",
    "Ecotech 3",
    "Sector 39 Noida",
    "Shahberi",
    "Dream Heights",
    "Sector 42",
    "Grace",
    "Paras Tierea",
    "The Rivulet Phase 1",
    "Sector 55 Noida",
    "Sector 35",
    "Amrapali Zodiac",
    "Jalalpur Greater Noida",
    "Eldeco Live By The Greens",
    "Green Villa 2",
    "RG Luxury Homes Phase 2",
    "Sector-37 Greater Noida",
    "Sector 36 Block B",
    "Supertech Ecociti",
    "Greater Noida West Noida",
    "Sector 39 Noida",
    "Sector 56 Noida",
    "Sector 56 Noida",
    "Sector 58",
    "ATS Picturesque Reprieves",
    "Sector 58",
    "Sector 58 Noida",
    "Sector 65",
    "Sector 65 Noida",
    "Sector 45",
    "Heritage Floors Villa",
    "Amrapali Princely Estate",
    "Vihaan Galaxy",
    "Sector 55 Noida",
    "Sector 55 RWA",
    "Sector 55 Noida",
    "Sector 56",
    "Sector 56",
    "Sector 1 Greater Noida",
    "Express View Apartments",
    "Stellar Jeevan",
    "Sector 40 Block E",
    "Jaypee Greens Garden Isles",
    "Sector 137",
    "Nirala Estate Phase 2",
    "Sector 28",
    "Sector 28",
    "Pearls Gateway Towers",
    "3C Lotus Boulevard Espacia",
    "Arihant Arden",
    "Sector 22 Noida",
    "Eta 2",
    "3C Lotus Boulevard Espacia",
    "SKA Greenarch",
    "Sector 22 Noida",
    "Sector 22 Noida",
    "Sector 23 Noida",
    "Sector 23 Noida",
    "Jaypee Kalypso Arcade",
    "ATS One Hamlet",
    "Sector 25",
    "Sector 40",
    "Sector 40",
    "Sector 40",
    "Sector 40",
    "Sector 134",
    "Sector 47",
    "Sector 48",
    "Sector 48 Noida",
    "Sector 48 Noida",
    "Alok Vihar Cooperative Society",
    "Antriksh Green",
    "M3M The Cullinan",
    "RWA Sector 26",
    "Godrej Golf Links",
    "Sector 27",
    "RG Residency",
    "Rise Resort Residences",
    "3C Lotus Boulevard Espacia",
    "Noida Extention",
    "Pari Chowk",
    "Gautam Budh Nagar",
    "Sector 151",
    "Sector 143",
    "3C Lotus Boulevard",
    "ACE City",
    "The Golden Palm",
    "Migsun Ultimo",
    "Omicron 1",
    "Radhika Green",
    "Omaxe ITC",
    "Amrapali Kingswood",
    "Arun Vihar",
    "Greater Noida West",
    "Sector 50 Noida",
    "Jal Vayu Vihar",
    "Sector XU 1 Greater Noida",
    "Noida Extention Greater Noida",
    "Taj Expressway",
    "Sector 82",
    "Alpha 2",
    "Aarcity Regency Park",
    "Sector 16",
    "Sunworld Vanalika",
    "Sector 15A",
    "SKA Metro Ville",
    "JM Orchid",
    "ATS Rhapsody",
    "Aba Cherry County",
    "Alpha 1 Block D Greater Noida",
    "Prit latest proj",
    "RG Luxury Homes",
    "Home and Soul F Premiere",
    "Supertech Eco Village",
    "Jaypee Greens Moon Court",
    "Dadri Ma Road",
    "Uppal Plumeria Garden Estate",
    "Techzone 4",
    "Aakriti Shantiniketan",
    "Techzone 4",
    "Antriksh Forest",
    "Arun Vihar",
    "Sector 126",
    "Jaypee Greens Klassic",
    "Sector 126",
    "Nagarjuna Appartmentss",
    "Omicron 1A Greater Noida",
    "Noida Extention",
    "Express Astra",
    "Gaur City Mall",
    "Eta 1",
    "Noida Extention Greater Noida",
    "Palm Grove Apartments",
    "Palm Grove Apartments",
    "Patel Neotown",
    "ATS Homekraft Happy Trails",
    "Sector 144",
    "Sneh Kunj Apartments",
    "Sneh Kunj Apartments",
    "Sharda University",
    "Swarna Nagri Block C",
    "Raksha Addela",
    "Amrapali Exotica",
    "Alok Vihar II",
    "CRC Sublimis",
    "Gaur City Plaza",
    "Jaypee Greens Pavilion Court",
    "Sethi Max Royal",
  ],

  Gurgaon: [
    "Sushant Lok-I",
    "DLF City Phase 2",
    "Godrej Nature Plus",
    "Luxury Builder Floors",
    "Experion Windchants",
    "DLF City Plot Phase 1",
    "Uppal Southend",
    "Pioneer Presidia",
    "Vipul World",
    "Emaar MGF Marbella",
    "Luxury Floors",
    "DLF City Phase 2",
    "Uppal Southend",
    "Bestech Altura",
    "Ashiana Amarah",
    "Suncity Township",
    "South City 1",
    "Uppal Southend",
    "Sushant Lok 3",
    "Luxurious Builder Floor",
    "Uppal Southend",
    "Bestech Altura",
    "Vatika Sovereign Park",
    "Sector 45 Block A Gurgaon",
    "DLF City Phase 1",
    "Smart World Orchard",
    "Emaar Emerald Estate",
    "RWA Sector 57",
    "Corona Optus",
    "Sector 28 Gurgaon",
    "All Punjabi Welfare Association",
    "M3M Golf Estate",
    "Ramprastha Primera",
    "MRG Crown",
    "Shapoorji Pallonji Joyville Gurugram",
    "M3M Merlin",
    "Tulip Monsella",
    "M3M Woodshire",
    "RWA Sushant lok",
    "Sushant Lok 1 Block C",
    "Sector 63A",
    "Vatika Sovereign Next",
    "Palam Vihar Pocket B Gurgaon",
    "Whiteland The ASPEN",
    "RWA Residential Society",
    "Signature Global Park 4 and 5",
    "Experion Windchants",
    "DLF The Summit",
    "PAREENA COBAN RESIDENCES",
    "Umang Monsoon Breeze Phase 2",
    "Sushant Lok 1 Block C",
    "Unitech Harmony",
    "Raheja Shilas",
    "Tata La Vida",
    "Sector 83",
    "Emaar Emerald Estate",
    "Salcon The Verandas",
    "Ireo The Grand Arch",
    "Salcon The Verandas",
    "Central Park Flower Valley Flamingo Floor",
    "Smart World Orchard",
    "M3M Antalya Hills Phase II",
    "Unitech Espace",
    "DLF City Plot Phase 2",
    "Ansal Versalia",
    "Godrej Meridien",
    "Sobha International City",
    "IREO Uptown",
    "Signature Global City 37D II",
    "Ansal API Esencia",
    "Luxury Builder Floors",
    "Sector 49",
    "Malibu Town",
    "DLF Crest",
    "Aqua Front Towers",
    "M3M Latitude",
    "SS The Leaf",
    "Central Park 2",
    "Tulip Monsella",
    "DLF Icon",
    "Sushant Lok 2",
    "Sobha International City",
    "Assotech Blith",
    "Sector 46",
    "Suncity",
    "Luxury Floors",
    "Dlf City Phase 4",
    "Saraswati Vihar",
    "M3M Merlin",
    "Signature Global Park",
    "Puri Emerald Bay",
    "Hero Homes",
    "BPTP MANSIONS PARK PRIME",
    "M3M Golf Estate",
    "Project Sushant Lok 1 Block C",
    "IREO Skyon",
    "Emaar Digi Homes",
    "Orchid IVY",
    "Vatika Gurgaon 21",
    "HUDA Authority Plots",
    "DLF Regal Gardens",
    "Birla Navya",
    "Unitech The World Spa",
    "Galaxy Apartment",
    "M3M Skycity",
    "DLF The Magnolias",
    "Sector 27",
    "Godrej Serenity",
    "Sector 38 Gurgaon",
    "Sushant Lok 1 Block C Gurgaon",
    "Zara Aavaas",
    "Gurgaon",
    "Signature Global City 93",
    "Saan Verdante",
    "Whiteland Blissville",
    "Conscient Heritage Max",
    "Whiteland Blissville",
    "Paras Dews",
    "Malibu Town",
    "Godrej Icon",
    "Ansals Sushant Floors",
    "Signature Global City 93",
    "DLF Phase 1 Arjun Marg",
    "Sector 43",
    "Unitech Cedar Crest",
    "RWA Residential Society",
    "Vatika Lifestyle Homes",
    "Block H",
    "Sector 63A",
    "M3M Crown Phase 1",
    "Emaar Palm Heights",
    "Bestech Park View City 2",
    "DLF New Town Heights 2",
    "Sidhartha NCR One",
    "Mayfield Garden",
    "Shree Vardhman Mantra",
    "Sector 57",
    "Sushant Lok Phase 3",
    "Ghata",
    "Ghata",
    "Bestech Park View Spa Next",
    "Bestech Park View Spa Next",
    "DLF City Plot Phase 1",
    "DLF The Primus",
    "Eros Wembley Estate",
    "Rajendra Park Block C",
    "DLF Ultima Phase II",
    "Elevate",
    "Park View City 1",
    "Ambience Mall",
    "Ambience Mall",
    "Ireo Victory Valley",
    "DLF Crest",
    "Om Nagar Sector 11",
    "IREO Skyon",
    "Surya Vihar Gurgaon",
    "Shree Vardhman Victoria",
    "Ardee City",
    "Signature Global City 79B 1",
    "Essel Towers",
    "M3M Marina",
    "Patel Nagar",
    "Emaar MGF Palm Studios",
    "Signature Global Park 4 and 5",
    "Bestech Park View Spa",
    "Gurgaon",
    "Chintamani",
    "Adani Samsara",
    "Spaze Privy 72",
    "Mahindra Aura",
    "Central Park",
    "Ansal Celebrity Homes",
    "Signature Global City 92",
    "Sector 23A Gurgaon",
    "Tulip Ivory",
    "Ramprastha The Edge Towers",
    "orchid petals",
    "Bestech Park View Residency",
    "DLF Nestle House",
    "Badshahpur Gurgaon",
    "Suncity Avenue 102",
    "The Adarsh Apartment",
    "Tata Primanti",
    "Sector 69",
    "Project Housing Board Colony",
    "Sector 22B Gurgaon",
    "DLF Imperial Residences",
    "Ansals Palam Vihar",
    "One Key Resiments",
    "Urban Oasis",
    "Godrej Iria",
    "Signature Global City 37D",
    "Central Park The Room",
    "Tatvam Villas",
    "Jyoti Park",
    "Emaar Gurgaon Greens",
    "Mahindra Luminare",
    "Smartworld One DXP",
    "BPTP park prime",
    "Sector 56",
    "Ardee City",
    "Anant Raj Manor Villas",
    "M3M Capital",
    "M3M Skywalk",
    "DLF New Town Heights 1",
    "Satya The Hermitage",
    "BPTP Terra",
    "Vipul Belmonte",
    "Guru Dronacharya Metro",
    "U Block",
    "U Block",
    "Chauma Village",
    "Emaar MGF Emerald Hills",
    "Ramprasta AWHO",
    "Om Vihar",
    "Tech Chand Nagar",
    "Dharampur",
    "Vatika India Next Plots",
    "Housing Board Colony",
    "Bajghera",
    "Ganpati Apartment",
    "LIG Colony",
    "LIG Colony",
    "Adani M2K Oyster Grande",
    "Laxman Vihar Industrial Area",
    "Urban Estate Sector 4 Gurgaon",
    "PWO Appartments",
    "PWO Appartments",
    "Ansals Palam Vihar",
    "Kenwood",
    "The Close South",
    "The Close South",
    "Orchid Island",
    "Essel Towers",
    "Mayfield Garden",
    "RWA Builder Floor",
    "Luxury Floors",
    "Ambience Mall",
    "Sector 41",
    "Aaron Ville",
    "Sector 41 Gurgaon",
    "Wazirpur",
    "Wazirpur",
    "DLF City Phase 3 Gurgaon",
    "Ashok Puri",
    "Suvidha Apartment",
    "DLF New Town Heights 2",
    "Vatika India Next",
    "Sector 42",
    "Sobha International City",
    "DLF City Phase 1",
    "Rail Vihar",
    "Sector 3 Block C1",
    "Tech Chand Nagar",
    "Laxman Vihar",
    "Krishna Colony",
    "Housing Board Colony",
    "Housing Board Colony",
    "Pioneer Park",
    "Bajghera",
    "Bajghera",
    "Sukhrali",
    "Central Park 3",
    "LIG Colony Gurgaon",
    "Rajiv Colony",
    "GLS Arawali Homes",
    "Shiv Colony",
    "Huda Colony Sector 4 Gurgaon",
    "Huda Colony Sector 4 Gurgaon",
    "Urban Estate Sector 4 Gurgaon",
    "Sector 70",
    "DLF Phase 1 Arjun Marg",
    "Vista Vilas",
    "Vista Vilas",
    "South City 2",
    "Signature Solera Apartment",
    "Smart World Gems",
    "Luxurious Builder Floor",
    "Project Sushant Lok 1 Block C",
    "Emaar MGF Emerald Hills",
    "Chintels Serenity",
    "Chintels Serenity",
    "Esencia",
    "Sector 43 Block D",
    "Unitech Vistas",
    "Sector 38",
    "Roots Courtyard",
    "Bestech Park View Ananda",
    "M2K Oyster Grande",
    "Esencia",
    "Pyramid Urban67A",
    "DLF New Town Heights 1",
    "M3M Antalya Hills Phase I",
    "Sector 7 Gurgaon",
    "Park Royal Apartment",
    "Godrej Meridien",
    "Spaze Privy 72",
    "Mapsko Mount Ville",
    "DLF Express Greens",
    "Nirvana Country",
    "Unitech Harmony",
    "Vatika Gurgaon 21",
    "NBCC Heights",
    "ILD Grand",
    "Sector 37C",
    "Vatika Primrose Floors",
    "Ansal Heights",
    "Uppal Southend",
    "Kibithu Villas",
    "RWA Residential Society",
    "Parsvnath Exotica",
    "M3M Skywalk",
    "DLF Regency Park 2",
    "Kashish Manor",
    "Green Wood Unitech",
    "Suncity Township Independent floor",
    "Indiabulls Centrum Park",
    "IREO Uptown",
    "Trump Tower",
    "Tata Gurgaon Gateway",
    "BPTP PARK SERENE",
    "Sector 47",
    "Ansal Height 86",
    "Eldeco Acclaim",
    "BPTP PARK SERENE",
    "BPTP PARK SERENE",
    "Orchid Mayfield Gardens",
    "Emaar The Palm Drive",
    "Uniworld Resorts",
    "Adani Samsara Vilasa",
    "Sector 105",
    "May Field Gardens Sector 51",
    "DLF The Belaire",
    "Golf Course Road",
    "RWA Residential Society",
    "Baani City Center",
    "Maple Heights",
    "Godrej Air",
    "SS Southend",
    "Tatvam Villas",
    "Sector 76",
    "DLF City Phase 3",
    "Sector 2",
    "Jyoti Park",
    "Sector 46 Gurgaon",
    "Dlf City Phase 4",
    "Ss Hibiscus 2",
    "Paras Irene",
    "Imperia Esfera",
    "Signature Global City 81",
    "Satya Element One",
    "Tashee Capital Gateway",
    "Palam Vihar",
    "DLF Alameda",
    "M3M Golf Hills Phase 1",
    "SRS Luxury Floors",
    "Sector 56 Gurgaon",
    "Sector 3 Block C1",
    "Ramprastha The Edge Towers",
    "South City 1",
    "Puri The Aravallis",
    "The Orchard",
    "Puri Emerald Bay",
    "Unitech Independent Floors",
    "C Dot Co operative Group Housing Society",
    "Green Woods City",
    "DLF Oakwood Estate",
    "ATS Tourmaline",
    "Zara Aavaas",
    "DLF Garden City The Primus",
    "Palam Vihar Gurgaon",
    "Rosewood City",
    "DLF City Phase 3 Gurgaon",
    "Experion Windchants",
    "Progressive Apartment",
    "Ireo Victory Valley",
    "Vatika Emilia floors",
    "South City",
    "Sector 95",
    "Signature The Roselia",
    "Sector 5",
    "Suncity",
    "Paragon Code 57",
    "New CRPF CGHS",
    "Hero Homes",
    "Orchid Island",
    "JMD Gardens",
    "Ramprastha The Rise",
    "Arihant Apartment",
    "Sector 102",
    "Park View Sanskruti",
    "Orchid Island",
    "Orchid IVY",
    "DLF City Plot Phase 1",
    "Trehan Luxury Floors",
    "Emaar Digi Homes",
    "Surbhi Apartment",
    "The Orchard",
    "Sushant Lok Builder Floors",
    "Anant Raj Estate",
    "Luxury Builder Floors",
    "Adani M2K Oyster Grande",
    "Delhi Gurgaon Expressway Gurgaon",
    "Vipul World",
    "Indiabulls Enigma",
    "Tashee Capital Gateway",
    "Sohna",
    "The Lilac",
    "DLF Exclusive Floors",
    "Sushant Lok-I",
    "Sushant Lok 1 Block C Gurgaon",
    "Lotus Homz",
    "Unitech Ivory Tower",
    "Emaar Emrald Floors Select",
    "SS The Leaf",
    "Ansal Sushant Lok CI",
    "Puri Emerald Bay",
    "Anant Raj Estate Plots",
    "Jyoti Park",
    "Mayfield Garden",
    "Patel Nagar",
    "The Estate Floors",
    "Emaar Emerald Hills",
    "Luxury Floors Gurgaon",
    "Unitech Greenwood City",
    "Sector 30",
    "Tulip White",
    "RWA DLF City Phase III",
    "DLF Crest",
    "DLF The Pinnacle",
    "Unitech Espace Nirvana Country",
    "Sector 27",
    "Gurgaon Floors",
    "Emaar Emerald Hills",
    "Dwarka Expressway",
    "Sector 47 Gurgaon",
    "Sushant Lok 3",
    "Suncity Platinum Towers",
    "Suncity Platinum Towers",
    "South City 1",
    "Parsvnath Exotica",
    "Surya Vihar Gurgaon",
    "IMT Manesar",
    "Signature Global City 37D",
    "Vatika India Next",
    "ATS Tourmaline",
    "Ardee City",
    "Shivpuri",
    "Lavanya Apartments",
    "Sector 22 Gurgaon",
    "DLF Beverly Park",
    "Signature The Serenas",
    "Unitech Fresco",
    "Godrej Nature Plus",
    "Ambience Creacions",
    "Sector 92",
    "Sector 37",
    "Ashiana Mulberry",
    "M3M Skywalk",
    "Pareena Sec68",
    "Unitech The World Spa",
    "New Colony",
    "Godrej Aria",
    "Ansal API Esencia",
    "Emaar Mgf Emerald Floors",
    "Hero Homes Phase 2",
    "Vodafone Belvedere Towers Rapid Metro",
    "Assotech Breeze",
    "Sector 3 Gurgaon",
    "Sector 95",
    "Shakti Nagar Gurgaon",
    "Sohna Gurgaon Road",
    "SBTL Caladium",
    "DLF Westend Height",
    "M3M Marina",
    "Palam Vihar Extension Gurgaon",
    "Sushant Lok 1 Block E",
    "Manesar",
    "Sector 11",
    "Sector 24",
    "Ambience Lagoon",
    "Ashok Vihar Phase 3 Extension",
    "Sector 55",
    "Sector 55",
    "DLF City Phase 3 Gurgaon",
    "Privy The Address",
    "Vatika Xpressions",
    "M3M Merlin",
    "Sector 67",
    "DLF City Independent Floors",
    "Unitech Greenwood City Apartment",
    "DLF Ridgewood Estate",
    "Sector 57 Block G",
    "Sector 86",
    "Sector 10 RWA",
    "Raisina Residenc",
    "Sector 15 Part 2",
    "Corona Optus",
    "Adani Samsara",
    "Malibu Town",
    "Bellevue Central Park 2",
    "Gurgaon",
    "M3M Antalya Hills Phase I",
    "Unitech Sunbreeze",
    "Apex Our Homes",
    "Raheja Vedaanta",
    "Gurgaon Rural Gurgaon",
    "M3M Capital",
    "Sohna Sector 5",
    "Ardee City",
    "Signature Global City 92 Phase 2",
    "Conscient One",
    "Sare Petioles",
    "Ireo Victory Valley",
    "Ireo The Corridors",
    "Ansal Esencia Sovereign Floors",
    "Trehan Luxury Floors",
    "Sector 67A",
    "Shivaji Nagar",
    "Shivaji Nagar",
    "Shivaji Nagar",
    "Elevate",
    "Pareena Micasa",
    "Godrej 101",
    "Sector 48",
    "New Shivalik Society",
    "Pyramid Fusion Homes",
    "Godrej 101",
    "Gwal Pahari",
    "Sector 77",
    "M3M Woodshire",
    "Sector 62",
    "Sector 8 Gurgaon",
    "Ompee Homes 14",
    "Sector 112",
    "Earth Copia",
    "Sector 40",
    "Sector 40",
    "Birla Navya",
    "Ansal Sushant Apartments",
    "Ansal Sushant Apartments",
    "Sector 57",
    "Rana Homes",
    "Sector 55 Gurgaon",
    "Sushant Lok Builder Floors",
    "SS The Leaf",
    "Saraswati Vihar",
    "M3M Merlin",
    "Sector 26",
    "Sector 26",
    "Sector 26 Gurgaon",
    "Subhash Nagar",
    "The Retreat",
  ],
};
const transactions = {
  Resale: [],
  "New Property": [],
  other: [],
};
const statuses = {
  "Ready to Move": [],
};
const facings = {
  "North - East": [],
  "North - West": [],
  North: [],
  East: [],
  South: [],
  West: [],
  "South - East": [],
  "South -West": [],
};
const owner = {
  Freehold: [],
  Leasehold: [],
  "Power Of Attorney": [],
  "Co-operative Society": [],
};

const PredictPrice = () => {
  const [errors, setErrors] = useState({});

  const [formData, setFormData] = useState({
    BHK: "",
    type: "",
    ownership: "",
    bathroom: "",
    balcony: "",
    city: "",
    location: "",
    Rate_per_sqft: "",
    bedroom: "",
    total_area: "",
    status: "",
    transaction: "",
    facing: "",
  });

  const [predictedPrice, setPredictedPrice] = useState(null);
  const [error, setError] = useState(null);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleCityChange = (e) => {
    const selectedCity = e.target.value;
    console.log("Selected city: ", selectedCity);
    setFormData({
      ...formData,
      city: selectedCity,
      location: "", // Reset location
    });
  //    const value = e.target.value;
  // setFormData((prev) => ({ ...prev, city: value }));
  // setErrors((prev) => ({
  //   ...prev,
  //   city: value ? "" : "City is required.",
  // }));
  };

  const handleownerChange = (e) => {
    setFormData({
      ...formData,
      ownership: e.target.value,
      // location: '', // Reset location when city changes
    });
  };

  const handletransactionChange = (e) => {
    setFormData({
      ...formData,
      transaction: e.target.value,
      // location: '', // Reset location when city changes
    });
  };
  const handlestatusChange = (e) => {
    setFormData({
      ...formData,
      status: e.target.value,
      // location: '', // Reset location when city changes
    });
  };
  const handlefacingChange = (e) => {
    setFormData({
      ...formData,
      facing: e.target.value,
      // location: '', // Reset location when city changes
    });
  };

  const handleLocationChange = (e) => {
    if (!formData.city) {
      alert("Please select a city first.");
      return;
    }
    const selectedLocation = e.target.value;
    console.log("Selected location: ", selectedLocation);
    setFormData({
      ...formData,
      location: selectedLocation,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

 const requiredSelectFields = [
    "city",
    "location",
    "transaction",
    "status",
    "facing",
    "ownership",
  ];

  const missingFields = requiredSelectFields.filter(
    (field) => !formData[field]?.trim()
  );

  if (missingFields.length > 0) {
    setError(
      `Please select values for: ${missingFields
        .map((field) => field.charAt(0).toUpperCase() + field.slice(1))
        .join(", ")}`
    );
    return;
  }



    // ---------------
    const isValid = Object.keys(formData).every((key) => {
      if (
        key === "Rate_per_sqft" ||
        key === "total_area" ||
        key === "bedroom" ||
        key === "balcony" ||
        key === "bathroom" ||
        key === "BHK"
      ) {
        return !isNaN(formData[key]) && formData[key] !== "";
      }
      return true; // Allow non-numeric fields to be empty or have any text
    });

    if (!isValid) {
      setError(
        "Please ensure all numerical fields are filled with valid numbers."
      );
      return;
    }

    // --------------
    try {
      const response = await axios.post(
        "https://ibuy-403u.onrender.com/api/evaluate-price",
        formData
      );
      setPredictedPrice(response.data.predictedPrice);
      setError(null);
    } catch (err) {
      setError("Error fetching predicted price. Please try again.");
      setPredictedPrice(null);
    }
  };

  return (
    // <div>
    //     <h1>Real Estate Price Predictor</h1>
    //     <form onSubmit={handleSubmit}>
    //         {Object.keys(formData).map((key) => (
    //             <div key={key}>
    //                 <label htmlFor={key}>{key.replace(/_/g, ' ')}:</label>
    //                 <input
    //                     type="number"
    //                     id={key}
    //                     name={key}
    //                     value={formData[key]}
    //                     onChange={handleChange}
    //                 />
    //             </div>
    //         ))}
    //         <button type="submit">Predict Price</button>
    //     </form>
    //     {predictedPrice !== null && (
    //         <div>
    //             <h2>Predicted Price: {predictedPrice}</h2>
    //         </div>
    //     )}
    //     {error && <p style={{ color: 'red' }}>{error}</p>}
    // </div>

    //         <div className="min-h-screen bg-gray-100 flex items-center justify-center px-6 py-8">
    //   <div className="bg-white shadow-lg rounded-lg p-8 max-w-lg w-full">
    //     <h1 className="text-2xl font-bold text-gray-800 text-center mb-6">
    //       Real Estate Price Predictor
    //     </h1>
    //     <form onSubmit={handleSubmit} className="space-y-4">
    //       {Object.keys(formData).map((key) => (
    //         <div key={key} className="flex flex-col">
    //           <label
    //             htmlFor={key}
    //             className="text-gray-700 font-medium mb-1 capitalize"
    //           >
    //             {key.replace(/_/g, ' ')}:
    //           </label>
    //           <input
    //             type="number"
    //             id={key}
    //             name={key}
    //             value={formData[key]}
    //             onChange={handleChange}
    //             className="border border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-blue-500 focus:outline-none"
    //             placeholder={`Enter ${key.replace(/_/g, ' ')}`}
    //           />
    //         </div>
    //       ))}
    //       <button
    //         type="submit"
    //         className="w-full bg-blue-600 text-white font-semibold py-3 rounded-lg hover:bg-blue-700 transition duration-300"
    //       >
    //         Predict Price
    //       </button>
    //     </form>
    //     {predictedPrice !== null && (
    //       <div className="mt-6 p-4 bg-green-100 text-green-800 rounded-lg text-center">
    //         <h2 className="text-lg font-medium">Predicted Price:</h2>
    //         <p className="text-2xl font-bold">{predictedPrice}</p>
    //       </div>
    //     )}
    //     {error && (
    //       <p className="mt-4 text-red-600 text-center font-medium">
    //         {error}
    //       </p>
    //     )}
    //   </div>
    // </div>

    <div className="min-h-screen flex flex-row gap-5  justify-center px-6 py-8 bg-black">
      <div className="bg-white shadow-2xl rounded-2xl p-8 flex-auto  w-full transform transition-transform duration-500 mt-10">
        {/* <h1 className="text-3xl font-extrabold text-gray-800 text-center tracking-wide">
      Real Estate Price Predictor
    </h1> */}
        <form
          onSubmit={handleSubmit}
          className="space-y-6 flex flex-row flex-wrap items-center justify-center p-6 rounded-lg"
        >
          <div className="flex flex-col mt-6 p-5">
            <label htmlFor="city" className="text-gray-700 font-semibold mb-2">
              City:
            </label>
            <select
              id="city"
              name="city"
              value={formData.city}
              onChange={handleCityChange}
              className="border border-gray-900 w-56 rounded-lg px-4 py-3 focus:ring-4 focus:ring-blue-300 focus:outline-none transition-all duration-300"
            >
              <option value="">Select a city</option>
              {Object.keys(cities).map((city) => (
                <option key={city} value={city}>
                  {city}
                </option>
              ))}
            </select>
            {/* <span className="text-red-500 text-sm">{errors.city}</span> */}
          </div>

          <div className="flex flex-col mt-6 p-5">
            <label
              htmlFor="location"
              className="text-gray-700 font-semibold mb-2"
            >
              Location:
            </label>
            <select
              id="location"
              name="location"
              value={formData.location}
              onChange={handleLocationChange}
              className="border border-gray-900 w-56 rounded-lg px-4 py-3 focus:ring-4 focus:ring-blue-300 focus:outline-none transition-all duration-300"
              disabled={!formData.city}
            >
              <option value="">Select a location</option>
              {formData.city &&
                [...new Set(cities[formData.city])].map((location) => (
                  <option key={location} value={location}>
                    {location}
                  </option>
                ))}
            </select>
          </div>

          <div className="flex flex-col mt-6 p-5">
            <label
              htmlFor="transaction"
              className="text-gray-700 font-semibold mb-2"
            >
              transaction:
            </label>
            <select
              id="transaction"
              name="transaction"
              value={formData.transaction}
              onChange={handletransactionChange}
              className="border border-gray-900 w-56 rounded-lg px-4 py-3 focus:ring-4 focus:ring-blue-300 focus:outline-none transition-all duration-300"
            >
              <option value="">Select a transaction</option>
              {Object.keys(transactions).map((transaction) => (
                <option key={transaction} value={transaction}>
                  {transaction}
                </option>
              ))}
            </select>
          </div>

          <div className="flex flex-col mt-6 p-5">
            <label
              htmlFor="status"
              className="text-gray-700 font-semibold mb-2"
            >
              status:
            </label>
            <select
              id="status"
              name="status"
              value={formData.status}
              onChange={handlestatusChange}
              className="border border-gray-900 w-56 rounded-lg px-4 py-3 focus:ring-4 focus:ring-blue-300 focus:outline-none transition-all duration-300"
            >
              <option value="">Select status</option>
              {Object.keys(statuses).map((status) => (
                <option key={status} value={status}>
                  {status}
                </option>
              ))}
            </select>
          </div>

          <div className="flex flex-col mt-6 p-5">
            <label
              htmlFor="facing"
              className="text-gray-700 font-semibold mb-2"
            >
              facing:
            </label>
            <select
              id="facing"
              name="facing"
              value={formData.facing}
              onChange={handlefacingChange}
              className="border border-gray-900 w-56 rounded-lg px-4 py-3 focus:ring-4 focus:ring-blue-300 focus:outline-none transition-all duration-300"
            >
              <option value="">Select a facing</option>
              {Object.keys(facings).map((facing) => (
                <option key={facing} value={facing}>
                  {facing}
                </option>
              ))}
            </select>
          </div>

          <div className="flex flex-col mt-6 p-5">
            <label
              htmlFor="ownership"
              className="text-gray-700 font-semibold mb-2"
            >
              ownership:
            </label>
            <select
              id="ownership"
              name="ownership"
              value={formData.ownership}
              onChange={handleownerChange}
              className="border border-gray-900 w-56 rounded-lg px-4 py-3 focus:ring-4 focus:ring-blue-300 focus:outline-none transition-all duration-300"
            >
              <option value="">Select owner</option>
              {Object.keys(owner).map((ownership) => (
                <option key={ownership} value={ownership}>
                  {ownership}
                </option>
              ))}
            </select>
          </div>

          {/* <div className="flex flex-col mt-6 p-5">
            <label htmlFor="transaction" className="text-gray-700 font-semibold mb-2">
              Property(New/Resale):
            </label>
            <select
              id="transaction"
              name="transaction"
              value={formData.transaction}
              onChange={handletransactionChange}
              className="border border-gray-900 w-52 rounded-lg px-4 py-3 focus:ring-4 focus:ring-blue-300 focus:outline-none transition-all duration-300"
            >
              <option value="">Select property condition</option>
              {Object.keys(transaction).map((transaction) => (
                <option key={transaction} value={transaction}>
                  {transaction}
                </option>
              ))}
            </select>
          </div> */}

          {Object.keys(formData).map(
            (key) =>
              key !== "city" &&
              key !== "location" &&
              key !== "transaction" &&
              key !== "status" &&
              key !== "facing" &&
              key !== "ownership" && (
                <div key={key} className="flex flex-col mt-6 p-5">
                  <label
                    htmlFor={key}
                    className="text-gray-700 font-semibold mb-2 capitalize"
                  >
                    {key.replace(/_/g, " ")}:
                  </label>
                  <input
                    type={
                      key === "Rate_per_sqft" ||
                      key === "total_area" ||
                      key === "bedroom" ||
                      key === "balcony" ||
                      key === "bathroom" ||
                      key === "BHK"
                        ? "number"
                        : "text"
                    }
                    id={key}
                    name={key}
                    value={formData[key]}
                    onChange={handleChange}
                    className="border border-gray-900 rounded-lg w-56 px-4 py-3 focus:ring-4 focus:ring-blue-300 focus:outline-none transition-all duration-300"
                    placeholder={`Enter ${key.replace(/_/g, " ")}`}
                  />
                </div>
              )
          )}

          {/* {Object.keys(formData).map((key) => (
        <div key={key} className="flex flex-col mt-6 p-5">
          <label
            htmlFor={key}
            className="text-gray-700 font-semibold mb-2 capitalize"
          >
            {key.replace(/_/g, ' ')}:
          </label>
          <input
             type={
              key === "Rate_per_sqft" || key === "total_area" || key === "bedroom" || key === "balcony" || key === "bathroom" || key === "BHK"
                  ? "number"
                  : "text"
          } 
            id={key}
            name={key}
            value={formData[key]}
            onChange={handleChange}
            className="border border-gray-900 rounded-lg px-4 py-3 focus:ring-4 focus:ring-blue-300 focus:outline-none transition-all duration-300"
            placeholder={`Enter ${key.replace(/_/g, ' ')}`}
          />
        </div>
      ))} */}
          <br />
          <button
            type="submit"
            className="w-4/5 bg-gradient-to-r from-blue-500 to-purple-600 text-white font-semibold py-3 rounded-lg shadow-lg hover:shadow-2xl transition-all duration-500 transform hover:translate-y-1"
          >
            Predict Price
          </button>
        </form>
        {/* {predictedPrice !== null && (
      <div
        className="mt-8 p-6 bg-gradient-to-r from-green-100 to-green-50 text-green-800 rounded-xl shadow-inner text-center"
        style={{
          animation: "fadeIn 1s ease-in-out",
        }}
      >
        <h2 className="text-lg font-bold">Predicted Price:</h2>
        <p className="text-3xl font-extrabold">{predictedPrice}</p>
      </div>
    )}
    {error && (
      <p
        className="mt-4 text-red-600 text-center font-medium animate-pulse"
      >
        {error}
      </p>
    )} */}
      </div>
      <div className=" flex-col  text-white min-w-96 bg-gradient-to-r from-blue-500 to-purple-600 bg-opacity-15 backdrop-blur-3xl shadow-2xl rounded-2xl p-8 mt-10 w-2/4">
        <div className="bg-gradient-to-r from-blue-500 to-purple-600 text-white p-6 rounded-lg shadow-lg m-auto">
          <h2 className="text-2xl font-bold mb-4">
            Unlock the Power of Predictive Insights!
          </h2>
          <p className="text-lg">
            Our state-of-the-art ML model delivers accurate property price
            predictions with cutting-edge technology. Designed for precision,
            powered by innovation.
          </p>
          <ul className="list-disc list-inside mt-4 text-sm space-y-2">
            <li>🚀 High accuracy with real-time adaptability</li>
            <li>🏠 Perfect for property buyers, sellers, and agents</li>
            <li>📊 Backed by advanced AI algorithms</li>
          </ul>
          <div className="mt-4">
            <h3 className="text-xl font-semibold mb-2">How to Use:</h3>
            <ol className="list-decimal list-inside text-sm space-y-1">
              <li>
                Enter property details such as location, BHK, total area, etc.
              </li>
              <li>
                Click the <strong>"Predict Price"</strong> button.
              </li>
              <li>Get instant, AI-powered price predictions!</li>
            </ol>
          </div>
          <div className="mt-6">
            <button className="bg-white text-blue-600 px-4 py-2 rounded-lg font-semibold shadow hover:bg-blue-100">
              Try Now
            </button>
          </div>
        </div>

        {predictedPrice !== null && (
          <div
            className="mt-5 p-6 bg-gradient-to-r from-green-100 to-green-50 text-green-800 rounded-xl shadow-inner text-center"
            style={{
              animation: "fadeIn 1s ease-in-out",
            }}
          >
            <h2 className="text-lg font-bold">Predicted Price:</h2>
            <p className="text-3xl font-extrabold">{predictedPrice}</p>
          </div>
        )}
        {error && (
          <p className="mt-4 text-red-600 text-center font-medium animate-pulse bg-white rounded-2xl p-2">
            {error}
          </p>
        )}
      </div>
    </div>
  );
};

export default PredictPrice;
